### ISSUE TITLE
Feature request: Romaji for hiragana and katakana

### ISSUE THREAD

**Issue by iyashi39** [kuanyui/Furiganaize#11]
Could you consider adding a romaji display for hiragana and katakana characters?
I've been looking for an extension that would add romaji for Japanese characters to the lyrics on youtube music and this one is working the best, all other extensions I have tried mess up the text size. I think it would be even better if it also could add romaji to hiragana and katakana.
Example screenshot:
![image](https://user-images.githubusercontent.com/38395954/185895381-ad5c528b-f013-443a-8fec-2ba15a145bab.png)

**Comment by kuanyui** [comment]
I have no free time can be spent to do this for free. Besides, this requirement is somewhat unnecessary; both furiganas are phonetic symbols (only 50 symbols), it would be worth and better to spend some free time to memorize them.

暇な時間がありませんですので、無償でこの機能を実装するの計画がありません。なお、この提案の意味がちょっとわからないです。カタカナとふりがなはもう表音文字ですので、少し暇な時間を使って暗記してください。
