### ISSUE TITLE
Incorrect reading is being considered in some cases.

### ISSUE THREAD

**Issue by andreslb151** [kuanyui/Furiganaize#2]
I tried Furiganaize with this 
https://www.animelyrics.com/jpop/sukima/bokunouto.jis

But, for instance, in this line:
"12時間経って並べたもんは紙クズだった"

For the "時" kanji it's considering the kunyomi reading "とき" instead of the onyomi one "ジ" (as it's refering to time).

In this case: "聞こえる雨の音", it simply won't print furigana for "聞" .

**Comment by kuanyui** [comment]
It's impossible to always get correct furigana by auto analysis. See [igo-javascript](https://github.com/shogo82148/igo-javascript)
