### ISSUE TITLE
Missing support for live-updated HTML

### ISSUE THREAD

**Issue by ZenaMel** [kuanyui/Furiganaize#5]
It would be nice if Furiganize worked on sites such as Twitch.tv where the DOM tree has to be traversed multiple times (for the chat box).

**Comment by kuanyui** [comment]
Please consider to make a PR. I have no interest to implement this because I don't need and I have no enough free time to make this for free.

**Comment by kuanyui** [comment]
This has been implemented in latest v0.6.0, need to be enabled manually in options.

If this helps you, please consider donation.

**Comment by nonetrix** [comment]
I think there might be a delay every time it tries to scan, this doesn't work well for subtitles. Could there be a feature added to customize this delay perhaps? If anyone feels like it, would help me a lot. Though might look into adding it myself though, if someone could point me to the code where this is done and where to add things to the UI it would help greatly. I think I have a powerful enough PC to parse it more without it slowing down much

**Comment by kuanyui** [comment]
> I think there might be a delay every time it tries to scan, this doesn't work well for subtitles. Could there be a feature added to customize this delay perhaps? If anyone feels like it, would help me a lot. Though might look into adding it myself though, if someone could point me to the code where this is done and where to add things to the UI it would help greatly. I think I have a powerful enough PC to parse it more without it slowing down much

1. I have no time to implement a feature I don't need, especially for free.
2. There's already a debounce delay timer before parsing sentences in DOM. A rough mechanism is: 
```
1. MutationObserver found something changed, start debounce delay timer.
2. Waiting for debounce delay timer timeout, if some other thing changed, restart this timer
3. When debounce timeout, pass all changed parts from tab -> background -> WebWorker (separated thread against `background` script) to analyze Japanese sentences (this process is asynchronized)
4. When the WebWorker finished, Worker will notify and send the furigana to the original tab.
```
3. Have you done a profiling and ensure where is the performance bottleneck? The most resource consuming part is Japanese sentences' analysis but it has been already done in a separated process / thread and should not slow down your computer, unless it's really too too slow.
