### ISSUE TITLE
Incorrect furigana entry

### ISSUE THREAD

**Issue by devio-at** [kuanyui/Furiganaize#6]
研究 is rendered as "ken-kiwamu" instead of expected "kenkyû"

source https://japanese.stackexchange.com/questions/86279/
verified https://ja.wikipedia.org/wiki/%E7%A0%94%E7%A9%B6%E5%93%A1

**Comment by kuanyui** [comment]
This is not the responsibility of this tool. See library [igo-javascript](https://github.com/shogo82148/igo-javascript).

**Comment by kuanyui** [comment]
See #9 #10 , the PR maybe could solve some of such case.
![Screenshot_20220823_184315](https://user-images.githubusercontent.com/1370070/186138951-cc90e114-88ed-45e4-908c-7e826c5de582.png)
