### ISSUE TITLE
Numbers with counter aren't correctly considered

### ISSUE THREAD

**Issue by EmmanuelMess** [kuanyui/Furiganaize#7]
Numbers with counter aren't correctly considered, like with 2日 it will have only にち above the 日 and ignore the 2.

https://github.com/shogo82148/igo-javascript/issues/4

**Comment by kuanyui** [comment]
Please provide a dictionary whose license compatible with MIT license, and it can solve such issue. Otherwise I won't have no time and interest to fix this.

**Comment by kuanyui** [comment]
Seem nobody want to spend their free time to solve this so close this issue.
